`='<'`?php namespace King\Orm\Generated;

use King\Orm\Base\BaseModel;
use King\Orm\Generated\`$schemaClassName`;

/**
 * Generated by king-orm/bin/korm.php
 *
 */
class `$tableClassName` extends BaseModel
{
    const SCHEMA = `$schemaClassName`::class;

`loop $fields $field $property
    /**
     * `$fieldComment[$field]`
     *
     * @var `$fieldType[$field]`
     */
`if isset($fieldDefault[$field])
    public $`$property` = '`$fieldDefault[$field]|addslashes`';
`else
    public $`$property`;
`/if
`/loop

    public function onInserted($id = null)
    {
        $this->_rowExist = true;
`if count($pk) === 1 && $auto
        $this->`$pkProperty[0]` = $id;
`/if
    }

    protected static $_mapping = [
`loop $fields $field $property
        `$schemaClassName`::FLD_`$field|strtoupper` => '`$property`',
`/loop
    ];
}
